package com.datazuul.eazy.bookscanner.gui;

import java.awt.Color;
import java.awt.Container;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.kordamp.ikonli.material2.Material2AL;
import org.kordamp.ikonli.swing.FontIcon;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Controller;

@Controller
public class MainFrame extends JFrame implements CommandLineRunner {

  public static final int ICON_SIZE = 18;

  private final ThumbnailsAndScanPanel thumbnailsAndScanPanel;

  /**
   * Creates new form MainFrame
   */
  public MainFrame(ThumbnailsAndScanPanel thumbnailsAndScanPanel) {
    super();
    this.thumbnailsAndScanPanel = thumbnailsAndScanPanel;
  }

  private FontIcon createFontIcon(Material2AL iconCode) {
    FontIcon exitIcon = new FontIcon();
    exitIcon.setIkon(iconCode);
    exitIcon.setIconSize(ICON_SIZE);
    return exitIcon;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    FontIcon exitIcon = createFontIcon(Material2AL.EXIT_TO_APP);
    exitIcon.setIconColor(Color.RED);
    exitMenuItem = new javax.swing.JMenuItem();
    helpMenu = new javax.swing.JMenu();
    aboutMenuItem = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("datazuul's Eazy BookScanner");
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo-datazuul-bookscan-32x32.png")).getImage());
    setName("mainFrame"); // NOI18N
    setPreferredSize(new java.awt.Dimension(1280, 800));

    fileMenu.setMnemonic(KeyEvent.VK_F);
    fileMenu.setText("File");
    fileMenu.setToolTipText("");

    exitMenuItem.setMnemonic(KeyEvent.VK_E);
    exitMenuItem.setText("Exit");
    exitMenuItem.setToolTipText("Exit application");
    exitMenuItem.setIcon(exitIcon);
    exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    helpMenu.setMnemonic(KeyEvent.VK_H);
    helpMenu.setText("Help");

    aboutMenuItem.setMnemonic(KeyEvent.VK_A);
    aboutMenuItem.setText("About");
    aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        aboutMenuItemActionPerformed(evt);
      }
    });
    helpMenu.add(aboutMenuItem);

    menuBar.add(helpMenu);

    setJMenuBar(menuBar);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
    System.exit(0);
  }//GEN-LAST:event_exitMenuItemActionPerformed

  private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
    // create a JTextArea
      JTextArea textArea = new JTextArea(10, 40);
      textArea.setText("datazuul's Eazy Bookscanner\n\n"
              + "Version 1.0.0\n\n"
      + "Homepage: https://github.com/datazuul/eazy-bookscanner");
      textArea.setEditable(false);
      
      // wrap a scrollpane around it
      JScrollPane scrollPane = new JScrollPane(textArea);
      
    ImageIcon imageIcon = new ImageIcon(MainFrame.class.getResource("/images/logo-datazuul-bookscan-48x48.png"));
      
      // display them in a message dialog
      JOptionPane.showMessageDialog(this, scrollPane, "About", JOptionPane.INFORMATION_MESSAGE, imageIcon);
  }//GEN-LAST:event_aboutMenuItemActionPerformed

  private void setup() {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
      }
    } catch (Exception ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem aboutMenuItem;
  private javax.swing.JMenuItem exitMenuItem;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JMenu helpMenu;
  private javax.swing.JMenuBar menuBar;
  // End of variables declaration//GEN-END:variables

  @Override
  public void run(String... args) throws Exception {
    setup();
    initComponents();
    thumbnailsAndScanPanel.init();
    Container contentPane = getContentPane();
    contentPane.add(thumbnailsAndScanPanel);
    contentPane.revalidate();
    contentPane.repaint();

    //This boots up the GUI.
    EventQueue.invokeLater(() -> this.setVisible(true));
  }
}
