package com.datazuul.eazy.bookscanner.gui;

import javax.swing.JLabel;

public class ThumbnailPanel extends javax.swing.JPanel {

  private int number;

  public ThumbnailPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    imagePanel = new com.datazuul.eazy.bookscanner.gui.ImagePanel();
    label = new javax.swing.JLabel();

    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

    imagePanel.setPreferredSize(new java.awt.Dimension(100, 150));

    label.setBackground(new java.awt.Color(255, 255, 255));
    //org.openide.awt.Mnemonics.setLocalizedText(label, org.openide.util.NbBundle.getMessage(ThumbnailPanel.class, "ThumbnailPanel.label.text")); // NOI18N
    label.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
    label.setOpaque(true);

    javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
    imagePanel.setLayout(imagePanelLayout);
    imagePanelLayout.setHorizontalGroup(
      imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(imagePanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(label)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    imagePanelLayout.setVerticalGroup(
      imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(label)
        .addContainerGap())
    );

    add(imagePanel);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.datazuul.eazy.bookscanner.gui.ImagePanel imagePanel;
  private javax.swing.JLabel label;
  // End of variables declaration//GEN-END:variables

  public ImagePanel getImagePanel() {
    return imagePanel;
  }

  public JLabel getLabel() {
    return label;
  }

  public int getNumber() {
    return number;
  }

  public void setNumber(int number) {
    this.number = number;
  }
}
